language: node_js
node_js:
  - "11"
npm:
  - "6"

script:
  - npm run build
  - npm run test

deploy:
  provider: npm
  email: $email
  api_key: $api_token
  on:
    tags: true
    all_branches: true
  skip_cleanup: true

cache:
  directories:
    - node_modules